apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: webserver
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    resources:
      requests:  # sets the min required resources to schedule the pod onto a node
        memory: "128Mi" # 128Mi = 128 mebibytes
        cpu: "500m"     # 500m = 500 milliCPUs (1/2 CPU)
      limits:    # sets the max required resources the node to allocate to the pod
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80