apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  ports:
  - port: 80 # target container port
  selector:  # target container labels
    app: webserver
  type: NodePort # allocates a port over this service on each node in the cluster